# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Startup Command
      id: hola
      uses: nisargshah1410/jsactiondemo@v1.6
      with:
        language: angular 
        cov: codecov
        file-path: ./**/target/site/jacoco/jacoco.xml
        
    - name: Echo Startup Command
      run: echo "${{ steps.hola.outputs.startupcmd }}"
    
    - name: Code Coverage
      run: echo "${{ steps.hola.outputs.coveragetest }}"
    
    - name: Checking for if condition
      uses: codecov/codecov-action@v1
      if : ${{ steps.hola.outputs.coveragetest == 'codecov'}}
      with:
        file: ${{ steps.hola.outputs.filep }}
    
    - name: Coverlet setting if condition
      if : ${{ steps.hola.outputs.coveragetest == 'coverlet'}}
      run : echo "dotnet test "${{ steps.hola.outputs.coverlet-settings }}""
      
    
    
    - name: installing dependencies
      run: |
        ${{ steps.hola.outputs.startupcmd }}
        
    - name: npm build, and test
      run: |
        #npm install
        npm run build --if-present
       # npm run test --if-present
    
